import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.tsx',
    ],

    theme: {
        extend: {
            colors: {
                "surface-container-high": "#e2e7ff",
                "primary": "#00246a",
                "outline-variant": "#c5c5d3",
                "primary-fixed-dim": "#b4c5ff",
                "primary-container": "#00389a",
                "tertiary": "#00311f",
                "primary-fixed": "#dbe1ff",
                "error-container": "#ffdad6",
                "on-primary-fixed-variant": "#003ea8",
                "surface-container-highest": "#dae2fd",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed": "#00174b",
                "on-secondary-container": "#57657b",
                "error": "#ba1a1a",
                "on-error": "#ffffff",
                "on-tertiary-fixed": "#002113",
                "tertiary-container": "#004a31",
                "on-surface-variant": "#444651",
                "tertiary-fixed": "#6ffbbe",
                "secondary-container": "#d5e3fd",
                "inverse-surface": "#283044",
                "secondary-fixed": "#d5e3fd",
                "on-background": "#131b2e",
                "on-error-container": "#93000a",
                "surface-tint": "#0053db",
                "tertiary-fixed-dim": "#4edea3",
                "on-secondary-fixed": "#0d1c2f",
                "surface": "#faf8ff",
                "on-tertiary": "#ffffff",
                "on-tertiary-container": "#27c38a",
                "on-secondary": "#ffffff",
                "secondary-fixed-dim": "#b9c7e0",
                "surface-container": "#eaedff",
                "on-primary": "#ffffff",
                "background": "#faf8ff",
                "surface-bright": "#faf8ff",
                "inverse-on-surface": "#eef0ff",
                "on-secondary-fixed-variant": "#3a485c",
                "secondary": "#515f74",
                "on-tertiary-fixed-variant": "#005236",
                "on-primary-container": "#8da9ff",
                "outline": "#757682",
                "surface-dim": "#d2d9f4",
                "surface-variant": "#dae2fd",
                "surface-container-low": "#f2f3ff",
                "inverse-primary": "#b4c5ff",
                "on-surface": "#131b2e",
                brand: {
                    base: '#f7f7f5',
                    primary: '#1f1a17',
                    secondary: '#087ab2',
                },
            },
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                manrope: ['Manrope', ...defaultTheme.fontFamily.sans],
                headline: ['Manrope'],
                body: ['Inter'],
                label: ['Inter'],
            },
        },
    },

    plugins: [forms],
};
